# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Telescope": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://jochym.github.io/osob/"

git_url = "https://github.com/jochym/osob/tree/main/"

def custom_doc_links(name): return None
