# AUTOGENERATED! DO NOT EDIT! File to edit: ../04_download.ipynb.

# %% auto 0
__all__ = []

# %% ../04_download.ipynb 2
import configparser
from fastcore.basics import patch
from os.path import expanduser
from astroquery.astrometry_net import AstrometryNet
from astroquery.exceptions import TimeoutError as ASTTimeoutError
from .core import Telescope
from .solver import Solver
from tqdm.auto import tqdm
