# AUTOGENERATED! DO NOT EDIT! File to edit: 02_process.ipynb (unless otherwise specified).

__all__ = []

# Cell
import configparser
from fastcore.basics import patch
from os.path import expanduser
from astroquery.astrometry_net import AstrometryNet
from astroquery.exceptions import TimeoutError as ASTTimeoutError
from .core import Telescope
from .solver import Solver